export const rentalData = [{
    id: 1,
    number: '001' ,
    name: 'Bulbasaur',
    type1: 'grass',
    type1clr: '#059509',
    type2: 'Poison',
    type2clr: '#9337d6',
    hp: '132',
    atk: '80',
    def: '81',
    spd: '77',
    spc: '97',
    upmove: 'LEECH SEED',
    uptype: 'Gr',
    upclr:  '#209922',
    leftmove: 'RAZOR LEAF',
    lefttype: 'Gr',
    leftclr: ' #209922', 
    rightmove: 'TOXIC',
    righttype: 'Po',
    rightclr: '#9337d6',
    downmove: 'BODY SLAM',
    downtype: 'N',
    downclr: '#bab4a9' } ,

{
    id: 2,
    number: '002' ,
    name: 'Ivysaur',
    type1: 'grass',
    type1clr: '#059509',
    type2: 'Poison',
    type2clr: '#9337d6',
    hp: '141',
    atk: '87',
    def: '89',
    spd: '85',
    spc: '106',
    upmove: 'RAZOR LEAF',
    uptype: 'Gr',
    upclr:  '#209922',
    leftmove: 'DOUBLE EDGE',
    lefttype: 'N',
    leftclr: '#bab4a9', 
    rightmove: 'SLEEP POWDER',
    righttype: 'Gr',
    rightclr: '#209922',
    downmove: 'GROWTH',
    downtype: 'N',
    downclr: '#bab4a9' } ,
    {
        id: 3,
        number: '003' ,
        name: 'Venusaur',
        type1: 'grass',
        type1clr: '#059509',
        type2: 'Poison',
        type2clr: '#9337d6',
        hp: '156',
        atk: '103',
        def: '104',
        spd: '102',
        spc: '121',
        upmove: 'LEECH SEED',
        uptype: 'Gr',
        upclr:  '#209922',
        leftmove: 'TAKE DOWN',
        lefttype: 'N',
        leftclr: '#bab4a9', 
        rightmove: 'POISON POWDER',
        righttype: 'Po',
        rightclr: '#9337d6',
        downmove: 'SOLARBEAM',
        downtype: 'Gr',
        downclr: '#209922' }
];